<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>FrankenToilet</AssemblyName>
    <Product>FrankenToilet</Product>
    <GUID>com.ultramodding.frankentoilet</GUID>
    <Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>14.0</LangVersion>
    <RootNamespace>FrankenToilet</RootNamespace>
    <CopyToBepInExPluginsDir>true</CopyToBepInExPluginsDir>
    
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <Import Project="Properties/DeployToPlugins.targets" />
  <Import Project="Properties/DevMode.targets" />
  <Import Project="Properties/References.props" />
  
  <ItemGroup>
    <PackageReference Include="UltraModding.PluginInfoGenerator" Version="4.*" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="Config\FrankenToilet.Config.fsproj" />
    <Compile Remove="Config\**" />
    <EmbeddedResource Remove="Config\**" />
    <None Remove="Config\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="alma\assets.bundle" />
    <None Remove="alma\scenes.bundle" />
    <None Remove="Bananastudio\frankentoiletbundle" />
    <None Remove="Bananastudio\gazimages" />
    <None Remove="Bananastudio\videoclips" />
    <None Remove="BlaixenU\assetblaixundle" />
    <None Remove="BlaixenU\BlaixenU" />
    <None Remove="bobthecorn\ultraclicker_assets_all.bundle" />
    <None Remove="Bryan\fuckyou.bundle" />
    <None Remove="dolfelive\dolfe.bundle" />
    <None Remove="doomahreal\veryuniqueassetsnametrust.bundle" />
    <None Remove="duviz\meow.bundle" />
    <None Remove="earthling\toiletonfire.bundle" />
    <None Remove="flazhik\ultrakill_sa.bundle" />
    <None Remove="greycsont\assetstealfromrhythmgame.bundle" />
    <None Remove="lakeull\lakeullsfunnybundle" />
    <None Remove="mercy\assets.bundle" />
    <None Remove="prideunique\aizoaizo" />
    <None Remove="somebilly\assets.bundle" />
    <None Remove="triggeredidiot\assets.bundle" />
    
    <EmbeddedResource Include="alma\assets.bundle" />
    <EmbeddedResource Include="alma\scenes.bundle" />
    <EmbeddedResource Include="Bananastudio\frankentoiletbundle" />
    <EmbeddedResource Include="Bananastudio\gazimages" />
    <EmbeddedResource Include="Bananastudio\videoclips" />
    <EmbeddedResource Include="BlaixenU\assetblaixundle" />
    <EmbeddedResource Include="BlaixenU\BlaixenU" />
    <EmbeddedResource Include="bobthecorn\ultraclicker_assets_all.bundle" />
    <EmbeddedResource Include="Bryan\fuckyou.bundle" />
    <EmbeddedResource Include="dolfelive\dolfe.bundle" />
    <EmbeddedResource Include="doomahreal\veryuniqueassetsnametrust.bundle" />
    <EmbeddedResource Include="duviz\meow.bundle" />
    <EmbeddedResource Include="earthling\toiletonfire.bundle" />
    <EmbeddedResource Include="flazhik\ultrakill_sa.bundle" />
    <EmbeddedResource Include="greycsont\assetstealfromrhythmgame.bundle" />
    <EmbeddedResource Include="lakeull\lakeullsfunnybundle" />
    <EmbeddedResource Include="mercy\assets.bundle" />
    <EmbeddedResource Include="prideunique\aizoaizo" />
    <EmbeddedResource Include="somebilly\assets.bundle" />
    <EmbeddedResource Include="triggeredidiot\assets.bundle" />
  </ItemGroup>

  <Target Name="CopyHarmonyExtensionDeps" AfterTargets="Build">
    <ItemGroup>
      <HarmonyDll Include="$(PkgHarmony_PatchExtensions)/lib/netstandard2.1/Harmony.PatchExtensions.dll" />
      <MonoModDll Include="$(PkgMonoMod_Backports)/lib/netstandard2.1/MonoMod.Backports.dll" />
      <MonoModILHelpersDll Include="$(PkgMonoMod_ILHelpers)/lib/netstandard2.1/MonoMod.ILHelpers.dll" />
    </ItemGroup>
    
    <Copy SourceFiles="@(HarmonyDll)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(MonoModDll)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(MonoModILHelpersDll)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
  
</Project>
